.gitignore
.vscode/settings.json
docs/01-index.md
docs/02-contributing.md
docs/03-process.md

adding a few pages, ignore local viscose settings

Feature documentation

---

fractal.config.js
public/theme/theme.css

Hi John 
I updated the logo and styling for variants navbar.

Theme updates

---

components/02-components/01-card/01-action-card/action-card.config.json
components/02-components/01-card/01-action-card/action-card.hbs
components/03-example-pages/poc-imports/poc-imports.config.json
components/03-example-pages/poc-imports/poc-imports.hbs
components/03-example-pages/poc-imports/poc-imports.readme.md

Hi John 
This is my POC for demonstrating how to "import/include" other components to create other components...and pages.
A problem I encountered when working on this: 
**How to pass plain/raw component code for imports and also use the same component file (with supporting markup) for documentation display.**
In the end, this poc demonstrates:
- how to reuse Context Data from another component
- how to use native Handlebar helpers
- how to '@' import components into another
Closes #24

Poc imports

---

components/02-components/03-banner/banner--rotating.hbs
components/02-components/05-call-to-actions/04-enrollment-call-to-action/enrollment-call-to-action.hbs
components/03-example-pages/01-home-page/home-page.hbs

starting to add {{ render }} directives for the components mocked-up so far, getting started with #60

adding rendered subcomponents to college home page

---

components/02-components/02-content-group/02-news-group/news-group.hbs

Reverts utsa-asc/college-dls#70

Revert "Sprint 02 news group"

---

docs/01-index.md

initial draft of welcome documentation

Sprint 01 documentation

---

components/02-components/01-card/04-news-card/news-card.config.json
components/02-components/01-card/04-news-card/news-card.hbs
components/02-components/01-card/04-news-card/news-card.readme.md

added News Card from SS DLS. Used Blog image as placeholder.

---

components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--2up.hbs
components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--blue-2up.hbs
components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--blue.hbs
components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--colors.hbs
components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--grey.hbs
components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--orange-2up.hbs
components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--orange.hbs
components/02-components/05-call-to-actions/01-call-to-action-buttons/call-to-action-buttons.config.json
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--2up-left.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--2up.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--3up-left.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--3up.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--blue-2up.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--blue-3up.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--blue.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--left.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--orange-2up.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--orange-3up.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image--orange.hbs
components/02-components/05-call-to-actions/02-call-to-action-image/call-to-action-image.hbs
components/03-example-pages/01-home-page/home-page.hbs

Sprint 03 updating college homepage imports

---

components/01-visual-styling/02-typography/09-table/table.config.json
components/01-visual-styling/02-typography/09-table/table.hbs

adding simple table

---

components/02-components/05-navigation/03-side-navigation/side-navigation.hbs
public/reference/accounting-faculty.html
public/reference/accounting.html
public/reference/behavior.html
public/reference/card-tiles.html
public/reference/contact.html
public/reference/department-accounting.html
public/reference/events.html
public/reference/functional.html
public/reference/index.html
public/reference/listing-component.html
public/reference/navigation-standard.html
public/reference/news.html
public/reference/policy-studies.html
public/reference/research.html
public/reference/scholarship.html
public/reference/style-component.html
public/reference/toc.html
public/reference/typography.html
public/reference/undergraduate-programs.html
public/reference/undergraduate-studies.html

discovered mobile issue, side menu plus items are un-clickable (inner expansion)

Fix side menu js

---

components/03-sections/02-navigation/01-site-navigation/site-navigation-admissions.hbs
components/03-sections/02-navigation/01-site-navigation/site-navigation.config.json

creating new variant for admissions nav

---

components/04-reference-pages/05-program-listing-page/program-listing-page.config.json
components/04-reference-pages/05-program-listing-page/program-listing-page.hbs
components/04-reference-pages/05-program-listing-page/program-listing-page.scss
src/scss/_vendor.scss

- adding sections and headings for program listing page
- updating content wrapper on the page
- optimizing class name and sass'ing the css

Sprint 08 program pages

---

components/03-sections/07-quickfacts/quickfacts.scss

padding addition from enrollment marketing

adjusting padding

---

components/01-visual-styling/03-button/01-text-link/text-link.readme.md
docs/02-contributing.md

A couple more spelling fixes

---

components/01-visual-styling/01-branding-standards/01-color/color.hbs

Updated color visual styling component structure. New styles/booststrap code. Geaux Tigers!

Visual Styling - Color Palette

---

components/01-visual-styling/01-branding-standards/03-borders/borders.hbs
components/01-visual-styling/01-branding-standards/04-global-header/global-header.readme.md
components/01-visual-styling/02-typography/04-intro/intro.hbs
components/01-visual-styling/02-typography/05-ordered-list/ordered-list--alt.hbs
components/01-visual-styling/02-typography/05-ordered-list/ordered-list.hbs
components/01-visual-styling/03-button/02-button/button.hbs
components/02-components/02-tab/tab.hbs
components/03-sections/02-navigation/01-site-navigation/site-navigation.readme.md
components/03-sections/03-banner/banner.hbs
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action.readme.md
components/03-sections/05-content-group/00-action-group/action-group.readme.md
components/03-sections/05-content-group/02-news-group/news-group.readme.md
components/03-sections/05-content-group/04-event-group/event-group.readme.md
components/03-sections/05-content-group/05-faculty-group/faculty-group.readme.md
components/03-sections/07-quickfacts/quickfacts.readme.md
docs/01-index.md
docs/03-process.md

Made some small changes that I noticed after doing a review.

After review changes

---

components/01-visual-styling/01-branding-standards/02-pattern/pattern.hbs

Updated background and pattern visual styling component to match color palette.

Background Patterns Visual Styling Update

---

components/03-sections/02-navigation/04-site-footer/site-footer.hbs
components/03-sections/02-navigation/04-site-footer/site-footer.readme.md
components/03-sections/02-navigation/04-site-footer/site-footer.scss

added example code, no new styles needed

addressses #227

---

components/02-components/04-profile/02-contact-callout/contact-callout--small.hbs
components/02-components/04-profile/02-contact-callout/contact-callout.hbs
components/02-components/04-profile/02-contact-callout/contact-callout.scss
src/scss/_vendor.scss

Not sure if I did this one right... 
Changes made -
1. Made small variant to fit into 3 & 4 col. 
2. Fixed typos. 
3. Added SCSS to component. 
4. In _vendor.scss file, I commented out selectors that I put into the component SCSS file.

Contact Callout  

---

components/03-sections/04-call-to-actions/04-gallery-call-to-action/gallery-call-to-action.hbs
components/03-sections/04-call-to-actions/04-gallery-call-to-action/gallery-call-to-action.scss

I think I fixed it, but let me know if it doesn't work.

Fixed an accessibility and icon issue

---

components/03-sections/07-quickfacts/quickfacts--2up.hbs
components/03-sections/07-quickfacts/quickfacts--3up.hbs
components/03-sections/07-quickfacts/quickfacts--4up.hbs
components/03-sections/07-quickfacts/quickfacts--6up.hbs
components/03-sections/07-quickfacts/quickfacts--blue.hbs
components/03-sections/07-quickfacts/quickfacts--grey.hbs
components/03-sections/07-quickfacts/quickfacts--orange.hbs
components/03-sections/07-quickfacts/quickfacts.hbs
components/03-sections/07-quickfacts/quickfacts.scss

Fixed typos, adjusted padding for consistency across all layouts.

Quickfacts 

---

components/01-visual-styling/02-typography/09-table/table.scss
src/scss/_vendor.scss

1. added table styles to table.scss
2. commented out table styles in _vendor.scss

visual-styling / typography / table

---

components/01-visual-styling/02-typography/03-callout/callout.config.json
components/01-visual-styling/02-typography/04-intro/intro.config.json
components/01-visual-styling/02-typography/04-intro/intro.scss

After discussion with team, changed the status of Intro and Callout components to 'prototype' since we are unsure if they will be needed. Also updated the styles for Intro component top border color.

Typography - Intro & Callout components status changed to Prototype

---

components/02-components/04-profile/04-faculty-bio/faculty-bio.scss
src/scss/_vendor.scss

I think I did this right, but let me know if I didn't.

Commented out in vendor and added to faculty-bio

---

components/01-visual-styling/02-typography/03-callout/callout.config.json
components/01-visual-styling/02-typography/04-intro/intro.config.json
components/01-visual-styling/02-typography/04-intro/intro.scss
components/01-visual-styling/02-typography/09-table/table.hbs
components/01-visual-styling/02-typography/09-table/table.readme.md

It seems like the table is already responsive, so I didn't add a variant. I did add more documentation to explain more about mobile responsiveness.

Added a little of documentation for mobile

---

components/01-visual-styling/02-typography/02-type/type.hbs
components/01-visual-styling/02-typography/02-type/type.scss

Removed some unnecessary code, removed 'medium' and 'semi-bold' weights because the classes don't even exist in the css, minor spelling correction. Will have to look into why 'light' font weight isn't displaying correctly.

Typography section corrections

---

components/04-reference-pages/03-department-secondary-page/department-secondary-page.hbs

Could probably do a better job of targeting the breakpoints, but this works for now.

Fixed issue of the form being cutoff

---

components/01-visual-styling/03-button/01-text-link/text-link.hbs
components/01-visual-styling/03-button/02-button/button.hbs
components/01-visual-styling/03-button/03-angled-button/angled-button--blue.hbs
components/01-visual-styling/03-button/03-angled-button/angled-button--large.hbs
components/01-visual-styling/03-button/03-angled-button/angled-button.hbs
components/01-visual-styling/03-button/03-angled-button/angled-button.scss
src/scss/_vendor.scss

Updated the angled buttons to use CSS to insert icons instead of an <i> tag.
Added correct classes to Angled Button - Large section (so they display correctly now). The classes existed but had not been applied yet for some reason.
Made some minor layout adjustments to Text Links (spaced the different ones out).
Added some missing CSS to vender scss file (hover class for the large angled buttons). Corrected a couple of spelling errors which may have caused some CSS to not apply correctly.

Updated Visual Styling - Buttons - Text/Angled/Etc.

---

components/01-visual-styling/03-button/03-angled-button/angled-button.scss
components/02-components/03-card/01-action-card/action-card--heading.hbs

Added one more line to angled button css to accomodate how they are used in the Action Card component. 
Also fixed a spelling error in the Action Card Heading component that was causing it to apply wrong CSS class.

Components - Action Card - Button Fix

---

components/01-visual-styling/03-button/03-angled-button/angled-button.scss
components/02-components/03-card/01-action-card/action-card.scss
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--2up.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--blue-2up.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--blue.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--colors.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--grey.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--orange-2up.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--orange.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons.scss
components/03-sections/04-call-to-actions/02-call-to-action-image/call-to-action-image--2up.hbs
components/03-sections/04-call-to-actions/02-call-to-action-image/call-to-action-image--3up.hbs
components/03-sections/04-call-to-actions/02-call-to-action-image/call-to-action-image.scss
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action--alt.hbs
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action.hbs

Added the gray hover color to the Call to Action buttons with color backgrounds to match the action buttons.
Included new btn-icon class as well so they are not using the <i> tag.
Adjusted the 2 button CTA CSS so btn-icon class works correctly.
Corrected some CSS issues/conflicts on the Action Card that were causing button to display incorrectly at smaller widths.

Call to Action button hover color updates, icons, Action Card fix

---

components/03-sections/07-quickfacts/quickfacts.readme.md
public/js/college-dls.min.js
public/js/vendor.min.js
public/theme/theme.css

Adding a new template/skeleton for documentation.  Mostly copied from https://designsystem.digital.gov, open to suggestions on the ordering and any things I missed.
At a high level, the notes section should be used to document correct usage and requirements for a component.  Technical documentation should be kept to a minimum or be placed as SCSS comments in the corresponding .scss file.
Target audience will be our college communicators and our editorial/writing staff at ASC (i.e.- our content creators).
https://utsa-asc.github.io/college-dls/section-documentation-template/components/detail/quickfacts--3up.html

Section documentation template

---

components/03-sections/03-banner/banner.scss

Fixes #267 - Removed underline for the icon link and added a blue hover.

DLS: Rotating Banner on hover properties

---

components/01-visual-styling/01-branding-standards/05-global-footer/global-footer.hbs
components/01-visual-styling/01-branding-standards/05-global-footer/global-footer.scss
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action.scss
src/scss/_variables.scss

Global footer alignment

---

components/03-sections/02-navigation/02-breadcrumb/breadcrumb.scss
components/03-sections/03-banner/banner.scss

adjusting breadcrumb wrapper to use the same variable we use for container padding
sass-ifying the breadcrumb definition
applying the same padding variable to our banner header tag

more fixes for #275

---

components/04-reference-pages/01-home-page/home-page.hbs
components/04-reference-pages/02-department-home-page/department-home-page.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-2.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-3.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page.hbs

resolving errors brought from renaming cta-image to cta-video

Cta media component

---

components/01-visual-styling/02-typography/01-headline/headline.hbs
components/01-visual-styling/02-typography/01-headline/headline.scss
components/01-visual-styling/02-typography/02-type/type.hbs

Added to scss file as h1, .h1 {} , and so on.

Updated Headings CSS to include H tags and h classes

---

components/03-sections/02-navigation/03-side-navigation/side-navigation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss

address #292 , lots of cleanup and sass-ifying

Sidebar id to class

---

components/04-reference-pages/02-department-home-page/department-home-page.hbs
components/04-reference-pages/02-department-home-page/department-home-page.scss
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-2.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-3.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page.hbs
components/04-reference-pages/10-institute-home-page/institute-home-page.hbs
components/04-reference-pages/11-institute-secondary-page/institute-secondary-page.hbs
public/js/college-dls.min.js
public/js/vendor.min.js

removing .heading-paragraph-design from page content areas, this should only be used by section level components and not leak into our default content styles for interior pages, addresses #300

Interior page content

---

components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--blue.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons.scss

fixes for #293, should not be assigning any extra classes inside the component for different color variants

cleaning up sass styles and removing classes from inside

---

fractal.config.js
public/theme/theme.css

Added the side navigation for nested variants, updated a few styles for readability.
For consideration to see if we like this version as opposed to having Variants nested underneath the Component in the main nav :P

Alt. Fractal Navigation with Nested Variants in Side Panel

---

components/01-visual-styling/02-typography/09-table/table--striped-blue.hbs
components/01-visual-styling/02-typography/09-table/table--striped-grey.hbs
components/01-visual-styling/02-typography/09-table/table--striped.hbs
components/01-visual-styling/02-typography/09-table/table.config.json
components/01-visual-styling/02-typography/09-table/table.readme.md
components/01-visual-styling/02-typography/09-table/table.scss

I think I got all the items listed in issue #278 and added some documentation.

Fixed items from issue 278 and added documentation

---

components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.scss

removed unneeded 0 left padding to make consistent with other variants

fixes padding for issue #295

---

components/01-visual-styling/03-button/02-button/button.hbs
components/01-visual-styling/03-button/02-button/button.scss

We could remove the min-width altogether, but I wanted to get everyone's thoughts. This addresses issue #322

changed max-width to min-width

---

components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--2up-left.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--2up.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--blue-2up.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--blue-left.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--blue.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--left.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--orange-2up.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--orange-left.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--orange.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--video.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.config.json
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.scss

fixes for issue #312, making the config content beefier for testing, removing large margins and making sure text color is consistent with variant background colors

312 cta type standardization

---

components/01-visual-styling/02-typography/09-table/table.scss
src/scss/_variables.scss

I should have listened to @prd409-utsa and made the grey a little lighter. 😉

Made the striped grey lighter to fix Tables #324

---

components/02-components/02-tab/tab.scss
components/03-sections/01-accordion/accordion.scss

removing heading scoped styles

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.scss

changing width to min-width, removing unused css

---

components/03-sections/07-quickfacts/quickfacts.scss

extra p margin bottom spacing found during our SDS review today, removing

during SDS review, found extra margin on p tags

---

components/01-visual-styling/04-utility/06-misc/misc.hbs
components/01-visual-styling/04-utility/06-misc/misc.scss
components/03-sections/03-banner/banner--blue.hbs
components/03-sections/03-banner/banner--stripe.hbs

Created additional class for a bottom left image clip mask (.clip-mask-left-bottom).
Added class to Utility > Misc. for reference. Added the class to the banners that use a bottom left clip mask (Banner blue, Banner striped). Replaced placeholder image so the clip patch can be viewed.

Components - Banner Image Clip Mask Update

---

components/01-visual-styling/01-branding-standards/05-global-footer/global-footer.hbs
components/01-visual-styling/01-branding-standards/05-global-footer/global-footer.readme.md
components/01-visual-styling/01-branding-standards/05-global-footer/global-footer.scss

Adjusted grid on last column and line-height

---

components/03-sections/07-quickfacts/quickfacts.scss

bad hardcoded max-width

---

components/03-sections/03-banner/banner--blue.hbs
components/03-sections/03-banner/banner--orange.hbs
components/03-sections/03-banner/banner--stripe.hbs

Fix for #336. Let me know if this works.

336 max height needed on banner components

---

components/01-visual-styling/04-utility/06-misc/misc.config.json
components/01-visual-styling/04-utility/06-misc/misc.hbs
components/01-visual-styling/04-utility/06-misc/misc.scss

we can now use these to assign clips to various positions on image elements
was going to use this general naming to apply to components too, but this may not work properly due to the different ratio of the div elements we clip.

standardizing clip classes for images

---

components/03-sections/02-navigation/03-side-navigation/side-navigation.config.json
components/03-sections/02-navigation/03-side-navigation/side-navigation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss
components/04-reference-pages/02-department-home-page/department-home-page.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-2.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page.hbs
src/scss/_vendor.scss

removed padding, found some stuff still in vendor.scss, also found some lingering no-padd in our reference pages (removed),  fixed a couple of more typos plus-icn > plus-icon minus-icn > minus-icon, these don't seem to have any styles attached, should not be a breaking change...

369 sidebar

---

components/02-components/04-profile/01-profile-card/profile-card--blue.hbs
components/02-components/04-profile/01-profile-card/profile-card.hbs
components/02-components/04-profile/01-profile-card/profile-card.scss

Added code to cover when there is no link

---

components/03-sections/03-banner/banner--blue.hbs
components/03-sections/03-banner/banner--orange.hbs
components/03-sections/03-banner/banner--stripe.hbs

Minor correction to applied img clip class on banners to reflect recent changes (clip-mask-bottom-left, etc.)

Minor updates to Banner CSS

---

components/01-visual-styling/04-color/01-color/color.config.json
components/01-visual-styling/04-color/01-color/color.scss
components/01-visual-styling/04-color/02-pattern/pattern.config.json

getting this in the right PR this time, and adding a background color variant as well
foreground: .white-b  (already existed previously)
background: .white-b-bg

not forgetting background color this time

---

components/02-components/03-card/03-content-card/content-card.scss

as requested, making border top consistent with accordion border (and tab?)
bumping highlight-card-link size

adjusting border size, link size

---

components/02-components/04-profile/03-profile-info/profile-info.hbs
components/02-components/04-profile/03-profile-info/profile-info.scss

Refactored SCSS, so the style isn't applied to ul

---

components/03-sections/02-navigation/03-side-navigation/side-navigation--heading.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation--orientation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.config.json
components/03-sections/02-navigation/03-side-navigation/side-navigation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss

@Uri-E, this was last week when we discussed this item in particular, but let me know if the styling on the first list item is enough.  Made the weight heavier and increase the font size slightly.

376 dls sidebar removal of heading

---

components/02-components/02-tab/tab.scss
components/02-components/03-card/01-action-card/action-card--heading.hbs
components/02-components/03-card/01-action-card/action-card.hbs
components/02-components/03-card/01-action-card/action-card.scss
components/02-components/03-card/02-event-card/event-card--horizontal-image.hbs
components/02-components/03-card/02-event-card/event-card--horizontal.hbs
components/02-components/03-card/02-event-card/event-card.scss
components/02-components/03-card/03-content-card/content-card.scss
components/02-components/03-card/04-news-card/news-card.scss
components/02-components/04-profile/01-profile-card/profile-card.scss
components/03-sections/01-accordion/accordion.scss
components/03-sections/05-content-group/02-news-group/news-group.scss
components/03-sections/05-content-group/03-event-list/event-list--image.hbs
components/03-sections/05-content-group/03-event-list/event-list.hbs
components/03-sections/05-content-group/03-event-list/event-list.scss
components/03-sections/05-content-group/04-event-group/event-group.scss
components/04-reference-pages/09-events-page/events-page.scss

Major changes for moving of top-border to the following components mentioned in issue #398:
- content card
- action card
- event card
- tab (no changes, just adjusting size)
- accordion
- news card
- profile card

398 orange line on card components + issue with button on card component

---

components/03-sections/03-banner/banner.scss

reverting yesterday deletion of .single-title-wrapper

restoring single-title-wrapper

---

components/02-components/03-card/03-content-card/content-card--visit.hbs
components/02-components/03-card/03-content-card/content-card.config.json
components/03-sections/05-content-group/01-content-list/content-list--visit.hbs

removing hard coded data from handlebars, moving image, url, url-text, heading and content to .config file

moving content into config for content-card--visit

---

components/03-sections/01-accordion/accordion.scss

Increased padding to right side of .accordion-button

---

components/01-visual-styling/01-typography/04-intro/intro--alt.hbs
components/01-visual-styling/01-typography/04-intro/intro.hbs
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action--no-image.hbs

adding two variants, one alt for intro (grey-bg) and one for enrollment (no-image)

208 dls branding standards typography intro additional variants

---

components/04-reference-pages/01-home-page/home-page.hbs
components/04-reference-pages/02-department-home-page/department-home-page.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-2.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-3.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page.hbs
components/04-reference-pages/04-RFI-page/RFI-page.hbs
components/04-reference-pages/05-faculty-listing-page/faculty-listing-page.hbs
components/04-reference-pages/06-program-listing-page/program-listing-page.hbs
components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
components/04-reference-pages/08-news-page/news-page.hbs
components/04-reference-pages/09-events-page/events-page.hbs
components/04-reference-pages/10-institute-home-page/institute-home-page.hbs
components/04-reference-pages/11-institute-secondary-page/institute-secondary-page.hbs
components/04-reference-pages/12-stacked-testing/stacked-testing.hbs
src/js/script.js
src/scss/_vendor.scss

Fixed Skip to Content behavior

---

components/01-visual-styling/02-button/01-text-link/text-link.hbs
components/01-visual-styling/02-button/01-text-link/text-link.scss
components/03-sections/08-content-callout/content-callout--blue.hbs
components/03-sections/08-content-callout/content-callout--gray.hbs
components/03-sections/08-content-callout/content-callout--orange.hbs
components/03-sections/08-content-callout/content-callout--white.hbs
components/03-sections/08-content-callout/content-callout.config.json
components/03-sections/08-content-callout/content-callout.hbs
components/03-sections/08-content-callout/content-callout.readme.md
components/03-sections/08-content-callout/content-callout.scss

3 variants: white (default), blue, orange

Added to Sections - Content Callout:

---

components/02-components/04-profile/02-contact-callout/contact-callout--small.hbs
components/02-components/04-profile/02-contact-callout/contact-callout.config.json
components/02-components/04-profile/02-contact-callout/contact-callout.hbs

just made this branch to update the status of this component from WIP to Exported.

updated components/04-profile/02-contact-callout to exported

---

components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
components/04-reference-pages/_faculty-profile-page-preview.hbs
public/js/profile-internal.js
public/js/profile.js
public/js/profile.js0
public/js/vendor-load.html
src/js/profile-internal.js
src/js/profile.js
src/js/vendor-load.html

- Cleaned up code in main faculty profile JS file
- Created internal JS file to be displayed in Cascade 
- Moved all internal errors to the internal file

Cleaned up faculty profile code with internal file

---

components/03-sections/01-accordion/accordion.scss

quick fix for accordion header extra margin

updating commented out code

---

components/02-components/04-profile/01-profile-card/profile-card.scss
components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.config.json

- added min-height for faculty profile
- change to exported for faculty profile

fix for lazy loading

---

components/02-components/03-card/01-action-card/action-card.readme.md
components/03-sections/05-content-group/00-action-group/action-group.readme.md

Added suggested documentation from #457

Added suggested documentation

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header.hbs

Also, there was an extra name declaration that I removed.

changed label for value to match up with input field

---

components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
src/js/profile-internal.js
src/js/profile.js

- Checks if Grants, Patents, and Clinical Trials are all blank
- Check to see if data is returned from the API
- Spelling fixes
- Journal check to make sure it has a valid value

Profile fixes I've found while adding to pages

---

components/03-sections/05-content-group/07-link-list/link-list.config.json
components/03-sections/05-content-group/07-link-list/link-list.hbs
components/03-sections/05-content-group/07-link-list/link-list.readme.md
components/04-reference-pages/10-institute-home-page/institute-home-page.hbs
components/04-reference-pages/12-stacked-testing/stacked-testing.config.json
components/04-reference-pages/12-stacked-testing/stacked-testing.hbs

Wrapped the component in section/container for row block layout, with maximum class for top and bottom margin (my-5). Also added list-link component to the Stacked Testing Page to check sizing.
DLS updates are ready for review.

content-group/link-list: 

---

components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
src/js/profile.js

- Was checking the wrong value for the presentation date which was causing it to show a default date 
- Cleaned accordion div code to help with readability

Fixed error for presentation date and cleaned code

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.scss

Pushed pop out menu down a little on mobile

---

components/03-sections/09-gallery/gallery.hbs

493 cms gallery links with the same name must have a similar purpose

---

components/02-components/03-card/04-news-card/news-card.scss

initial css changes for more flexible card image cropping

---

components/02-components/03-card/02-event-card/event-card.config.json
components/03-sections/05-content-group/03-event-list/event-list.scss
components/04-reference-pages/09-events-page/events-page.config.json
components/04-reference-pages/09-events-page/events-page.hbs

- Fixed issue #502 
- Changed to exported in JSON file for event components
- Added Event List to Events reference page

Made blue overlay same size regardless of content

---

components/02-components/03-card/02-event-card/event-card--horizontal-blue.hbs
components/02-components/03-card/02-event-card/event-card--horizontal-image-blue.hbs
components/02-components/03-card/02-event-card/event-card.config.json
components/03-sections/05-content-group/03-event-list/event-list--image.hbs
components/03-sections/05-content-group/03-event-list/event-list.config.json
components/03-sections/05-content-group/03-event-list/event-list.hbs
components/03-sections/05-content-group/03-event-list/event-list.scss
components/03-sections/05-content-group/04-event-group/event-group.config.json
components/04-reference-pages/09-events-page/events-page.hbs
components/04-reference-pages/09-events-page/events-page.readme.md

I removed the gutter for the column with the image. Feel free to jump in and make any edits if you think it would look better a certain way.

Added blue variants

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation--heading.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.hbs

adjusting DLS to match the output code from CMS formats, namely, the output of aria-labels in the navigation formats

adding back aria-labels from navigation systems to DLS from CMS

---

components/02-components/03-card/04-news-card/news-card.scss

Let me know if you think the height should be larger or smaller.

Added a 200px height

---

components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
src/js/profile.js

I was going to add the chronological order in this PR, but it seems like a bit much. I'll do another PR shortly.

Added limit for each area

---

components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs

removing older SS class names and updating sections to more closely match CMS out from College-PROTOTYPE/_cms/formats/components/[profileInfo](https://walledev.it.utsa.edu/entity/open.act?id=c616225281736a1b48bb59f1c2317d49&type=format)
resolves issue #539

getting hbs in sync with CMS format output, adjusting col responsiveness

---

src/js/profile-internal.js
src/js/profile.js

updating Invalid UUID error message to Data Not Found

updating UUID error message

---

components/03-sections/10-icon-callout/icon-callout--blue.hbs
components/03-sections/10-icon-callout/icon-callout--orange.hbs
components/03-sections/10-icon-callout/icon-callout--white.hbs
components/03-sections/10-icon-callout/icon-callout.config.json
components/03-sections/10-icon-callout/icon-callout.hbs
components/03-sections/10-icon-callout/icon-callout.readme.md
components/03-sections/10-icon-callout/icon-callout.scss

Please let me know your thoughts. I was wondering if it should be part of the content callout section, but it seems different. Also, open to color and layout suggestions.

544 dls contact callout wicons

---

package.json

dependency updates and version bump, few days late, but still keeping it named jan 2023. =)

Release jan 2023

---

components/04-reference-pages/01-home-page/home-page.hbs
components/04-reference-pages/02-department-home-page/department-home-page.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-2.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-3.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page.hbs
components/04-reference-pages/04-RFI-page/RFI-page.hbs
components/04-reference-pages/05-faculty-listing-page/faculty-listing-page.hbs
components/04-reference-pages/06-program-listing-page/program-listing-page.hbs
components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
components/04-reference-pages/08-news-page/news-page.hbs
components/04-reference-pages/09-events-page/events-page.hbs
components/04-reference-pages/10-institute-home-page/institute-home-page.hbs
components/04-reference-pages/11-institute-secondary-page/institute-secondary-page.hbs
components/04-reference-pages/12-stacked-testing/stacked-testing.hbs
components/04-reference-pages/13-portfolio-projects-page/portfolio-projects-page.hbs
components/04-reference-pages/14-internal-error-page/internal-error-page.hbs
src/js/page.js

- removed div from reference pages hbs
- removed js cover fadeout

removing loading spinner

---

components/03-sections/03-banner/banner--video.hbs
components/03-sections/03-banner/banner.scss
components/04-reference-pages/02-department-home-page/department-home-page.hbs
components/04-reference-pages/02-department-home-page/department-home-page.readme.md
src/js/bundle/college-dls-umd.js

complete rewrite based on: https://startbootstrap.com/snippets/video-header
may need some more fallbacks for image when video is unavailable, needs moar testing, closes issue #586

586 dls banner video component

---

components/03-sections/03-banner/banner--rotating.hbs
components/03-sections/03-banner/banner.scss
gulpfile.js
src/js/bundle/college-dls-umd.js

- updated data-bs-ride attribute for carousel autopla
- updating default javascript code for carousel play/pause to act more like video pause/play controls

fixes for carosel controls, missing data attributes

---

src/js/bundle/college-dls-umd.js

whoops, this was hanging javascript on pages w/o a carousel, my attempts to write vanilla javascript...

on do carousel stuff if a carousel exists

---

components/03-sections/03-banner/banner--logo.hbs
components/03-sections/03-banner/banner--video.hbs
components/03-sections/03-banner/banner.config.json
components/03-sections/03-banner/banner.scss
public/utsa/images/placeholder-500-500.svg
src/js/bundle/college-dls-umd.js

[variant in operation on WALLEDEV](https://walledev.it.utsa.edu/entity/open.act?id=7f51c8cd81736a1b003cf7c3d7c446f4&type=page)

initial mockup of banner logo variant

---

components/01-visual-styling/01-typography/06-unordered-list/unordered-list.config.json
components/01-visual-styling/01-typography/06-unordered-list/unordered-list.hbs

The errors have been fixed for unordered list content.

Updated Unordered list to fix errors in content displayed

---

components/01-visual-styling/02-button/03-angled-button/angled-button--blue.hbs
components/01-visual-styling/02-button/03-angled-button/angled-button--large.hbs
components/01-visual-styling/02-button/03-angled-button/angled-button.hbs
components/01-visual-styling/02-button/03-angled-button/angled-button.scss
components/_button-preview.hbs

Adding css styles for hover of angled buttons. These will match the default "Button" hover styles on blue-bg and orange-a11y-bg.

Updating angle button hover color on colored backgrounds

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.hbs
components/03-sections/02-navigation/01-site-navigation/site-navigation.scss

May need some testing on sites that don't have orange enrollment links.

added rule for overflowing on last links on nav

---

components/03-sections/11-image-collage/image-collage--blue-left-orange-bg.hbs
components/03-sections/11-image-collage/image-collage--blue-left.hbs
components/03-sections/11-image-collage/image-collage--blue-right-grey-bg.hbs
components/03-sections/11-image-collage/image-collage--orange-left-grey-bg.hbs
components/03-sections/11-image-collage/image-collage--orange-left.hbs
components/03-sections/11-image-collage/image-collage--orange-right-blue-bg.hbs
components/03-sections/11-image-collage/image-collage--orange.hbs
components/03-sections/11-image-collage/image-collage.config.json
components/03-sections/11-image-collage/image-collage.hbs

Added the standard button link design to the content area of Image Collage component

Added CTA Button to all the image collage variants

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header.hbs
components/02-components/01-form/form--blue.hbs
components/02-components/01-form/form--degree-blue.hbs
components/02-components/01-form/form--degree.hbs
components/02-components/01-form/form--faculty-blue.hbs
components/02-components/01-form/form--faculty.hbs
components/02-components/01-form/form--program-blue.hbs
components/02-components/01-form/form--program.hbs
components/02-components/01-form/form--publication-blue.hbs
components/02-components/01-form/form--publication.hbs
components/02-components/01-form/form--research-blue.hbs
components/02-components/01-form/form--research.hbs
components/02-components/01-form/form--rfi-blue.hbs
components/02-components/01-form/form--rfi-orange.hbs
components/02-components/01-form/form--rfi.hbs
components/02-components/01-form/form--subscribe-blue.hbs
components/02-components/01-form/form--subscribe.hbs
components/02-components/01-form/form.hbs
components/04-reference-pages/04-RFI-page/RFI-page.hbs
components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
components/04-reference-pages/15-error-page-not-found/error-page-not-found.hbs

Updated labels to comply with accessibility standards example included with this issue description.

Updated labels to comply with accessibility standards

---

components/02-components/04-profile/01-profile-card/profile-card.config.json
components/02-components/04-profile/01-profile-card/profile-card.scss
components/03-sections/05-content-group/05-faculty-group/faculty-group.config.json
components/03-sections/05-content-group/06-profile-group/profile-group--compact.hbs
components/03-sections/05-content-group/06-profile-group/profile-group.config.json
components/03-sections/05-content-group/06-profile-group/profile-group.scss

4-up profile group variant, only change needed was to adjust the hardcoded min-height for the image.  Also putting all the profile-card-list css into this component (profile-group) scss file instead of in the smaller organism profile-card

adding compact variant

---

components/02-components/03-card/01-action-card/action-card.readme.md
components/02-components/03-card/02-event-card/event-card.readme.md
components/02-components/03-card/03-content-card/content-card.readme.md
components/02-components/03-card/04-news-card/news-card.readme.md
components/02-components/04-profile/01-profile-card/profile-card.readme.md
components/02-components/04-profile/02-contact-callout/contact-callout.readme.md
components/02-components/04-profile/03-profile-info/profile-info.readme.md
components/02-components/04-profile/04-faculty-bio/faculty-bio.readme.md
components/03-sections/02-navigation/04-site-footer/site-footer.readme.md
components/03-sections/03-banner/banner.readme.md
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.readme.md
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action.readme.md
components/03-sections/05-content-group/00-action-group/action-group.readme.md
components/03-sections/05-content-group/01-content-list/content-list.readme.md
components/03-sections/05-content-group/03-event-list/event-list.readme.md
components/03-sections/06-blockquote/blockquote.readme.md
components/03-sections/09-gallery/gallery.readme.md
components/03-sections/11-image-collage/image-collage.readme.md

Moved footer media requirements to the CTA and made sure they are in list form!

Updates to 566 based off comments

---

components/03-sections/02-navigation/02-breadcrumb/breadcrumb.scss

just need a simple nest here "ul" not >ul, fixes #639

correctly target breadcrumb ul

---

components/03-sections/05-content-group/08-faculty-slider/faculty-slider--blue.hbs
components/03-sections/05-content-group/08-faculty-slider/faculty-slider--grey.hbs
components/03-sections/05-content-group/08-faculty-slider/faculty-slider--orange.hbs
components/03-sections/05-content-group/08-faculty-slider/faculty-slider.config.json
components/03-sections/05-content-group/08-faculty-slider/faculty-slider.hbs
components/03-sections/05-content-group/08-faculty-slider/faculty-slider.readme.md
components/03-sections/05-content-group/08-faculty-slider/faculty-slider.scss
components/04-reference-pages/01-home-page/home-page.readme.md

- Fixed header color on blue bg
- Marked as exported
- Added link in reference 
- Removed padding-top on button
- Added lazy loading since it was added in the CMS

Fix for heading color on blue bg

---

docs/03-process.md

Update the Process tab to include step by step documentation on how new component/new variant requests are handled.
Please review and provide feedback if anything looks out of place.
Geaux Tigers.

Cdls-design-process-documentation

---

components/03-sections/02-navigation/05-back-to-top/back-to-top.config.json
components/03-sections/02-navigation/05-back-to-top/back-to-top.hbs
src/js/back-to-top.js

- Removed blank style attribute
- Added document.ready function to fix flicker
- Changed to exported

A couple updates after implementation

---

components/04-reference-pages/16-faculty-directory-search/faculty-directory-search--compact.hbs
components/04-reference-pages/16-faculty-directory-search/faculty-directory-search.config.json
components/04-reference-pages/16-faculty-directory-search/faculty-directory-search.hbs
components/04-reference-pages/16-faculty-directory-search/faculty-directory-search.md
components/04-reference-pages/16-faculty-directory-search/faculty-directory-search.scss
components/04-reference-pages/_faculty-directory-search-preview.hbs
src/js/faculty-listing-search.js

I could add more people if it looks weird with the same people.

Added directory search to DLS

---

components/01-visual-styling/02-button/03-angled-button/angled-button.scss

fixes regression in issue #649

fixing double bg color nested items

---

components/03-sections/01-accordion/accordion.hbs
components/03-sections/01-accordion/accordion.scss

I added a class, but I thought about adding the following scss:
`	@media print{
.collapse {
display: block !important;
height: auto !important;
}
.accordion-button:after {
content: " ";
color: $white;
}		
}`
Let me know when y'all think.

I added a class for accordions to show on print

---

components/03-sections/05-content-group/07-link-list/link-list.config.json
components/03-sections/05-content-group/07-link-list/link-list.readme.md

- Added documentation on how to use in the WYSIWYG
- Changed to exported since it's part of the template

Added documentation on how to access the link list

---

components/03-sections/05-content-group/06-profile-group/profile-group.scss
components/04-reference-pages/16-faculty-directory-search/faculty-directory-search--compact.hbs
components/04-reference-pages/16-faculty-directory-search/faculty-directory-search.hbs
src/js/faculty-listing-search.js

Minor updates to accommodate staff additions

---

components/03-sections/02-navigation/05-back-to-top/back-to-top--left.hbs
components/03-sections/02-navigation/05-back-to-top/back-to-top.hbs

Sorry for not checking this on my last commit.

Added a script tag, so the button shows in the component window

---

components/02-components/01-form/form.scss

enlarging arrow by about 10px

---

components/02-components/03-card/02-event-card/event-card.scss
components/03-sections/03-banner/banner--logo-center.hbs
components/03-sections/03-banner/banner.config.json
components/03-sections/03-banner/banner.scss

banner-logo-center variant for utsa arts

---

components/01-visual-styling/01-typography/02-type/type.scss
components/02-components/04-profile/01-profile-card/profile-card.scss
components/03-sections/02-navigation/02-breadcrumb/breadcrumb.scss
components/03-sections/02-navigation/04-site-footer/site-footer.scss

Updated some link styles that still had
issues with color contrast on hover. Breadcrumbs,
subfooter social nav, and profile cards. Few CSS tweaks here and there.

Link style updates, Contd.

---

components/03-sections/02-navigation/03-side-navigation/side-navigation--no-action-buttons.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation--orientation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss

Added a new item for no action buttons to help test

---

components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--blue.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--orange.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.scss

Added additional CSS for CTA H tags used on different background variants. Added subheaders to some CTA image components to view how subheaders are handled.

CTA image H tag CSS updates for background variants

---

docs/01-index.md

small doc updates updating BS version and other dependency versions

small doc updates, dep version updates

---

components/04-reference-pages/17-search-results-page/search-results-page.config.json
components/04-reference-pages/17-search-results-page/search-results-page.hbs
components/04-reference-pages/17-search-results-page/search-results-page.md
components/04-reference-pages/17-search-results-page/search-results-page.scss

rest of the stuff should happen in CMS:
-rewiring header search bar to this page (iff it exists via a $_.locatePage())
-setting up custom search domain in _blocks/setup config, pulling it thru to this page via formats

simple mock-up, custom search is setup to filter to provost.utsa.edu

---

components/02-components/04-profile/02-contact-callout/contact-callout--default-unlinked.hbs
components/02-components/04-profile/02-contact-callout/contact-callout--small-unlinked.hbs
components/02-components/04-profile/02-contact-callout/contact-callout--small.hbs
components/02-components/04-profile/02-contact-callout/contact-callout.config.json
components/02-components/04-profile/02-contact-callout/contact-callout.hbs
components/02-components/04-profile/02-contact-callout/contact-callout.scss
components/04-reference-pages/02-department-home-page/department-home-page.scss
components/04-reference-pages/12-stacked-testing/stacked-testing.scss

Updated Contact Card styles to match those of
standard faculty profile cards. Added link styles/icons, updated some text styles. 
If linked, name will have link icon and be orange. If not, won't have icon and be blue.

Contact Card, Contact Card Small Updates

---

components/06-wysiwyg/01-style-rules/style-rules--link-rules.hbs
components/06-wysiwyg/01-style-rules/style-rules.config.json
components/06-wysiwyg/01-style-rules/style-rules.hbs
components/06-wysiwyg/01-style-rules/style-rules.readme.md
components/06-wysiwyg/01-style-rules/style-rules.scss
components/06-wysiwyg/_wysiwyg-page-preview.hbs
components/06-wysiwyg/wysiwyg.config.yml
src/scss/site-wysiwyg.scss

Let me know if there is a better way to target items or if we should add additional rules to the stylesheet.

Added rules and separate style sheet for WYSIWYG

---

components/06-wysiwyg/01-style-rules/style-rules--link-rules.hbs
components/06-wysiwyg/01-style-rules/style-rules.hbs
components/06-wysiwyg/01-style-rules/style-rules.readme.md
components/06-wysiwyg/01-style-rules/style-rules.scss

- More coverage for Outlook safelinks
- Updated documentation language
- Fixed headers for the image section since I had the incorrect language

A couple minor fixes

---

components/01-visual-styling/01-typography/04-ordered-list/ordered-list.scss
components/01-visual-styling/01-typography/05-unordered-list/unordered-list.scss
components/02-components/02-tab/tab.hbs
components/03-sections/01-accordion/accordion.hbs
components/03-sections/01-accordion/accordion.scss

Updated accordion and tabs to allow for full-width of content area when adding a table. Updates to CSS.

Updated accordion and tabs to allow for full-width

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header.scss
components/03-sections/02-navigation/01-site-navigation/site-navigation.scss
src/js/bundle/college-dls-umd.js
src/scss/_variables.scss
src/scss/site.scss

first PR for merging an issue fix for colds-bs-dark-mode branch,  also has the current js fix for DM functionality on walledev until #774 is resolved

773 dm site navigation styling for dark mode is still blue

---

components/01-visual-styling/01-typography/06-table/table--striped-blue.hbs
components/01-visual-styling/01-typography/06-table/table--striped-grey.hbs
components/01-visual-styling/01-typography/06-table/table--striped.hbs
components/01-visual-styling/01-typography/06-table/table.scss

adjusting colors for striped grey and blue to $white-b background and $blue for th elements, addresses #782

782 dls striped table with a th on a row doesnt meet color contrast standards

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.hbs
components/03-sections/02-navigation/01-site-navigation/site-navigation.scss

I made some updates, but I'm not sure about the colors. I tried to make it similar to the side nav colors, but I could adjust if this is what Uriel wasn't envisioning.

768 dm mobile navigation menu not styled for dark mode

---

components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--grey-2up.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--grey-3up.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--grey-left.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media--grey.hbs
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.config.json
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.scss

- Added grey variant
- Added SASS section for grey variant

784 dm cta with grey background missing in cta media area

---

components/01-visual-styling/01-typography/02-type/type.scss
components/01-visual-styling/04-color/01-color/color.scss
components/03-sections/01-accordion/accordion.scss
src/scss/_dark-mode-data.scss
src/scss/_dark-mode-media.scss

Updated some more header class and general text/color styles for dark mode. I think this should take care of text outside of <p> tags and header classes that are added to headers without a color background (although we might need to make additions and updates if I missed something).

DM text and header style updates

---

components/02-components/02-tab/tab.hbs
components/02-components/02-tab/tab.scss

- added rule for `ol li`
- added HTML for testing

797 dm ordered list not displaying correctly for tabs

---

components/04-reference-pages/08-news-page/news-page.hbs
components/04-reference-pages/08-news-page/news-page.scss
components/04-reference-pages/09-news-listing-page/news-listing-page.hbs
components/04-reference-pages/09-news-listing-page/news-listing-page.scss

clears issue #772, small class additions for news source and date

772 dm blog index color contrast with date and dark mode

---

components/01-visual-styling/01-typography/02-type/type.scss

please note, example issue has typo 'cart-text', closes #798

minimal styling for regular bs cards

---

components/04-reference-pages/04-RFI-page/RFI-page.scss

Minor fix to RFI form page because of DM text changes (white text back to blue).

RFI page in DM

---

components/03-sections/01-accordion/accordion.hbs
components/03-sections/01-accordion/accordion.scss

closes #780, styling for text and anchor in and out of p tags, slight adjustment to padding at different breakpoints

DM style updates for accordion-body-content in dark mode

---

components/01-visual-styling/01-typography/02-type/type.scss

fixing grey-bg nesting, closes #798

---

components/03-sections/02-navigation/03-side-navigation/side-navigation.scss

re-ordering dm styles to fix sidebar issues on mobile

---

components/04-reference-pages/08-news-page/news-page.scss
components/04-reference-pages/09-news-listing-page/news-listing-page.scss

cleaning up news listing page styles

---

components/01-visual-styling/01-typography/06-table/table.hbs
components/01-visual-styling/01-typography/06-table/table.scss

- Added `th` rules 
- I added a rule for tables not using our table classes
- Rule for links on striped background

803 dm table without any of our classes doesnt display correctly

---

components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons.scss

- Removed error in SASS 
- Added stricter rules for p tags

815 dm default cta text has color contrast issues

---

components/02-components/02-tab/tab.config.json
components/02-components/02-tab/tab.hbs
components/02-components/02-tab/tab.scss
components/03-sections/05-content-group/06-link-list/link-list.scss

820 dm link list in tabs has blue hover and blue text

---

components/04-reference-pages/20-bootstrap-testing/bootstrap-component-testing.config.json
components/04-reference-pages/20-bootstrap-testing/bootstrap-component-testing.hbs
components/04-reference-pages/20-bootstrap-testing/bootstrap-component-testing.scss
src/scss/_variables.scss

closes #766, had to disable a few of the color vars we brought in when setting up 5.3

766 dm some alert styling not working

---

components/02-components/02-tab/tab.hbs
components/03-sections/01-accordion/accordion.hbs
components/03-sections/05-content-group/06-link-list/link-list.scss

821 dm link list in accordion has low contrast

---

components/01-visual-styling/05-branding-standards/02-global-footer/global-footer.scss
components/02-components/04-profile/01-profile-card/profile-card.scss
components/03-sections/07-quickfacts/quickfacts.scss
components/03-sections/11-image-collage/image-collage.scss
components/04-reference-pages/10-events-page/events-page.scss

DM CSS updates for a few bugs I found. Calendar 
page daily and weekly views, collage button,
quickfacts headers and minor text updates. 
Calendar might need some review after it's updated since I'm kinda guessing which classes apply where, but I think it should work OK.

DM text and button bugs

---

src/scss/_dark-mode-wysiwyg.scss
src/scss/site-fractal.scss
src/scss/site-wysiwyg.scss
src/scss/site.scss

- defined new dark-mode-wysiwyg to make sure we do not define a dark theme on site-wysiwyg.scss, closes #791

791 dm custom styles not showing in wysiwyg

---

components/03-sections/01-accordion/accordion.hbs
components/03-sections/01-accordion/accordion.scss

- added rule for `ol li` in sass
- added sample ordered list in HTML

830 dm ordered lists in accordions not displaying correctly

---

components/03-sections/01-accordion/accordion.hbs
components/03-sections/01-accordion/accordion.scss

- Added buttons to HTML view
- Added rules for buttons

834 dm hover on buttons in accordions are blue on blue

---

components/04-reference-pages/17-error-page-not-found/error-page-not-found.hbs
components/04-reference-pages/17-error-page-not-found/error-page-not-found.scss

- Made edits to make the HTML similar to what is in the CMS
- Added dark mode rule

833 dm google cse input field contrast is off

---

components/04-reference-pages/_event-calendar-page-preview.hbs

not sure how this was working, forgot to include corrected version in the last commit

841 dls remove labjs dependency for events calendar

---

components/02-components/02-tab/tab.hbs
components/02-components/02-tab/tab.scss

- Added HTML code for buttons
- Added coverage for buttons in tabs

857 dls buttons on tabs aren't displaying correctly

---

components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.config.json
components/03-sections/04-call-to-actions/02-call-to-action-media/call-to-action-media.scss

- Added coverage for divs
- Noticed a header wasn't showing, so added coverage for that too
Let me know if there is a better way to do this.

850 dm text not in certain tags not displaying correctly for cta w/media

---

components/01-visual-styling/01-typography/06-table/table--striped-blue.hbs
components/01-visual-styling/01-typography/06-table/table--striped-grey.hbs
components/01-visual-styling/01-typography/06-table/table--striped.hbs
components/01-visual-styling/01-typography/06-table/table.hbs
components/01-visual-styling/01-typography/06-table/table.scss

- Added coverage for ul li, ol li, and p tags
- Added examples to HTML code

848 dm p and ul tags in table cells are not meeting contrast guidelines

---

components/03-sections/05-content-group/07-faculty-slider/faculty-slider--blue.hbs
components/03-sections/05-content-group/07-faculty-slider/faculty-slider--grey.hbs
components/03-sections/05-content-group/07-faculty-slider/faculty-slider--orange.hbs
components/03-sections/05-content-group/07-faculty-slider/faculty-slider.hbs
components/03-sections/05-content-group/07-faculty-slider/faculty-slider.scss

- Added code to cover for items not linked
- Made sure correct orange was used in dark mode

859 dm faculty slider a11y orange isn't passing color contrast rules on name field

---

components/04-reference-pages/02-department-home-page/department-home-page.scss

DM CSS for department details and header.

Department information DM fix

---

components/04-reference-pages/20-event-calendar/event-calendar.scss

adjusted font-weight and font-size for prev/next month day text

---

components/01-visual-styling/01-typography/02-type/type.scss

Added DM CSS for ol and ul within grey backgrounds.

853-dm-ordered-list-has-a-contrast-error-on-grey-background

---

components/01-visual-styling/01-typography/06-table/table--striped-blue.hbs
components/01-visual-styling/01-typography/06-table/table--striped-grey.hbs
components/01-visual-styling/01-typography/06-table/table--striped.hbs
components/01-visual-styling/01-typography/06-table/table.hbs
components/01-visual-styling/01-typography/06-table/table.scss
components/03-sections/01-accordion/accordion.hbs
components/03-sections/01-accordion/accordion.scss

- Updated sass coverage for headings in p tags
- Updated HTML pages for testing coverage

854 dm tables with headers on rows not displaying correctly

---

components/01-visual-styling/01-typography/06-table/table.hbs
components/01-visual-styling/01-typography/06-table/table.scss
components/02-components/02-tab/tab.hbs

- Refactored sass for better readability
- Added more coverage for tabs

Simplified sass and added more info to tabs

---

public/theme/color-modes.js

It looked like the color mode was trying to be set, but the iframe wasn't loaded. I added a listener event when the page loads to add a color mode if the iframe hasn't loaded yet.

870 dm color mode not being set and error in the console

---

components/03-sections/05-content-group/07-faculty-slider/faculty-slider.scss

- changed the link color for the grey background to blue to fix a11y issue
Let me know if I should change the color of the arrows or anything else.

Changed link color to blue to fix a11y issue

---

components/01-visual-styling/01-typography/02-type/type.scss

- Added coverage for p, code, and pre tags

Added coverage for a couple of tags

---

components/01-visual-styling/01-typography/06-table/table--striped-blue.hbs
components/01-visual-styling/01-typography/06-table/table--striped-grey.hbs
components/01-visual-styling/01-typography/06-table/table--striped.hbs
components/01-visual-styling/01-typography/06-table/table.hbs
components/01-visual-styling/01-typography/06-table/table.scss

Let me know if the hover color should be different.

Added coverage for buttons on hover in tables

---

components/03-sections/05-content-group/07-faculty-slider/faculty-slider.scss

Let me know if any of the others should be adjusted.

Changed no link color to pass a11y standards

---

components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.config.json
components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.hbs

Learn More image - fixed img src so image shows in Live DLS

906-side-nav-news

---

components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.config.json
components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.hbs

additional bug fixes for my hbs/config changes

906 side nav news

---

components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.hbs
components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.scss

cleaned up li to remove span class so styles are a bit cleaner

906-side-nav-news-list

---

components/03-sections/08-content-callout/content-callout--blue.hbs
components/03-sections/08-content-callout/content-callout--orange.hbs
components/03-sections/08-content-callout/content-callout--white.hbs
components/03-sections/08-content-callout/content-callout.hbs
components/03-sections/08-content-callout/content-callout.scss

- Added action buttons to handlebar files
- Changed hard-coded regular buttons to reference buttons
- Added SASS coverage for action buttons 
- Added coverage for headers on blue background since they weren't showing in light mode
One question I did have was whether the white background should be dark in dark mode.

Added coverage for action buttons for dark mode

---

src/scss/provost-styling.scss

- CSS output in CMS: https://walledev.it.utsa.edu/entity/open.act?id=fec600ff81736a1b24239e55c0251d9a&type=file
- Sample page: https://walledev.it.utsa.edu/entity/open.act?id=fde827e681736a1b24239e5557bcc8b5&type=page

Created new Sass file for blockquote and sidebar news

---

components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.scss
components/03-sections/12-timeline/timeline.scss

Added dark mode styles to news sidebar. Also made a small correction to timeline spacing, since I'm already here >.>

Dark Mode styles for news sidebar

---

components/01-visual-styling/01-typography/06-table/table--striped-blue.hbs
components/01-visual-styling/01-typography/06-table/table--striped-grey.hbs
components/01-visual-styling/01-typography/06-table/table--striped.hbs
components/01-visual-styling/01-typography/06-table/table.hbs
components/01-visual-styling/01-typography/06-table/table.scss
components/03-sections/01-accordion/accordion.hbs
components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.config.json
components/04-reference-pages/08-news-page/news-page.config.json
components/04-reference-pages/20-bootstrap-testing/bootstrap-component-testing.hbs
src/scss/_variables.scss

- Added fixes for Bootstrap tables
- Referenced buttons instead of hard-coding them
- Added grey button fixes for tables in dark mode
- Fixed error in the terminal for the status of the news sidebar
- Fixed images on bootstrap testing page

Added some tables fixes

---

src/js/timeline.js

I had to add some hide/show logic for the default section.

JS updates to Timeline for CMS

---

components/03-sections/06-blockquote/blockquote--inline.hbs
components/03-sections/06-blockquote/blockquote.scss
components/04-reference-pages/08-news-page/news-page--sidebar.hbs
components/04-reference-pages/08-news-page/news-page.hbs
components/04-reference-pages/08-news-page/news-page.scss
src/scss/provost-styling.scss

- Added an inline blockquote to add inside pages 
- Updated news sidebar page to add tags, social share, inline blockquote, and images  
- Imported news page styling for provost news items

Added some styling to match up with Uriel's mock-up

---

components/04-reference-pages/22-timeline-page/timeline-page.config.json
components/04-reference-pages/23-datatables/datatables.config.json
components/04-reference-pages/23-datatables/datatables.hbs
components/04-reference-pages/23-datatables/datatables.md
components/04-reference-pages/23-datatables/datatables.scss
components/04-reference-pages/_datatables-preview.hbs
package.json
src/js/bundle/datatables.js
src/scss/cms-internal.scss
src/scss/site-fractal.scss
src/scss/site-wysiwyg.scss
src/scss/site.scss

- Added DataTables to DLS - I'm using a CDN to bring in styles and JS, but I could change it if you would like.
- Changed the status of Timeline since it's now exported

Added Datatables to DLS

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.hbs

Added some padding to the main nav logo in the nav bar html. That seems to be a good fix to solve the light/dark mode on hover spacing issue.

Main nav logo fix for issue 925

---

package.json
src/js/bundle/college-dls-umd.js
src/scss/_variables.scss
src/scss/cms-internal.scss
src/scss/site-fractal.scss
src/scss/site-wysiwyg.scss
src/scss/site.scss

will need some testing on walledev, but the replacement seems to work with the form components in the dis
https://utsa-asc.github.io/college-dls/934-dls-select2-is-adding-a-b-tag-with-a-role-of-presentation-on-the-drop-down-icon/components/detail/faculty-directory-search--default.html
https://utsa-asc.github.io/college-dls/934-dls-select2-is-adding-a-b-tag-with-a-role-of-presentation-on-the-drop-down-icon/components/detail/form--default.html
Testing this branch also requires a `npm install`

934 dls select2 is adding a b tag with a role of presentation on the drop down icon

---

components/03-sections/01-accordion/accordion.config.json
components/03-sections/01-accordion/accordion.hbs
components/03-sections/09-gallery/gallery--video.hbs
components/03-sections/09-gallery/gallery.config.json
components/03-sections/09-gallery/gallery.hbs
components/03-sections/12-timeline/timeline.config.json

Let me know if the spacing or colors should be adjusted.

Added optional subheader and description

---

components/03-sections/01-accordion/accordion.hbs

Let me know if you have any adjustments.

Minor adjustments to header and bottom margin

---

components/02-components/01-form/form.scss

Updated dark mode form SCSS for consistency. Removed border on dropdown and kept text area white throughout.

Resolving Issue 942 - Form SCSS updates

---

components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
components/04-reference-pages/11-events-listing-page/events-listing-page.config.json
components/04-reference-pages/19-search-results-page/search-results-page.config.json
src/js/utsa-discovery.js

- Switched the UUID to someone who has presentations with a null value
- Added code to skip a presentation if the name is null
- Changed the Events Listing page and Search Results page to exported since they are in production now

Added code to skip presentation if the name is null

---

components/03-sections/02-navigation/04-side-navigation-news/side-navigation-news.scss
components/04-reference-pages/22-timeline-page/timeline-page.scss
src/scss/_font.scss
src/scss/cms-internal.scss

I'm not sure if we have to do this for each upgrade or if there is a better way to do this.

Added new value for font awesome upgrade

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header--rebrand.hbs
components/01-visual-styling/05-branding-standards/01-global-header/global-header.scss
src/js/bundle/college-dls-umd.js

will be adding here for my global header updates today/tomorrow

removing orange bar

---

components/04-reference-pages/01-home-page/home-page.hbs
components/04-reference-pages/02-department-home-page/department-home-page.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-2.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page--landing-3.hbs
components/04-reference-pages/03-department-secondary-page/department-secondary-page.hbs
components/04-reference-pages/04-RFI-page/RFI-page.hbs
components/04-reference-pages/05-faculty-listing-page/faculty-listing-page.hbs
components/04-reference-pages/06-program-listing-page/program-listing-page.hbs
components/04-reference-pages/07-faculty-profile-page/faculty-profile-page.hbs
components/04-reference-pages/08-news-page/news-page--sidebar.hbs
components/04-reference-pages/08-news-page/news-page.hbs
components/04-reference-pages/09-news-listing-page/news-listing-page.hbs
components/04-reference-pages/10-events-page/events-page.hbs
components/04-reference-pages/11-events-listing-page/events-listing-page.hbs
components/04-reference-pages/12-institute-home-page/institute-home-page.hbs
components/04-reference-pages/13-institute-secondary-page/institute-secondary-page.hbs
components/04-reference-pages/15-portfolio-projects-page/portfolio-projects-page.hbs
components/04-reference-pages/16-internal-error-page/internal-error-page.hbs
components/04-reference-pages/17-error-page-not-found/error-page-not-found.hbs
components/04-reference-pages/18-faculty-directory-search/faculty-directory-search--compact.hbs
components/04-reference-pages/18-faculty-directory-search/faculty-directory-search.hbs
components/04-reference-pages/19-search-results-page/search-results-page.hbs
components/04-reference-pages/21-event-calendar/event-calendar.hbs
components/04-reference-pages/22-timeline-page/timeline-page--small.hbs
components/04-reference-pages/22-timeline-page/timeline-page.hbs
components/04-reference-pages/23-datatables/datatables.hbs
components/04-reference-pages/24-action-card-search/action-card-search--compact.hbs
components/04-reference-pages/24-action-card-search/action-card-search--grey.hbs
components/04-reference-pages/24-action-card-search/action-card-search.hbs

per issue #1007 , updating reference pages, making sure they are showing both header/footer rebrands

updating reference page global headers

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header--rebrand.hbs
components/01-visual-styling/05-branding-standards/02-global-footer/global-footer--rebrand-secondary.hbs
components/01-visual-styling/05-branding-standards/02-global-footer/global-footer--rebrand.hbs
components/03-sections/02-navigation/01-site-navigation/site-navigation.scss
src/js/bundle/college-dls-umd.js

closes issue #1014 , #1005, and removes box-shadow on top nav that shows up visually in dark mode

1014 dls change the value to a placeholder attribute for the input field on the global header

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header.scss
components/01-visual-styling/05-branding-standards/02-global-footer/global-footer--rebrand-secondary.hbs
components/01-visual-styling/05-branding-standards/02-global-footer/global-footer--rebrand.hbs
components/01-visual-styling/05-branding-standards/02-global-footer/global-footer.scss

Added CSS updates for :focus and :hover stylings in the footer. Also updated a few stylings to align with the new UTSA branding standards on the Rebrand footer (even if we're not using that one, just in casies).

Footer CSS updates and fixes

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header--rebrand.hbs

adding aria-labels to news and myUTSA in the global header
