utsa-asc/college-dls

components/02-components/02-content-group/02-news-group/news-group.hbs
components/02-components/02-content-group/02-news-group/news-group.scss

If the quotes are left off, it seems to work.
Example - 
prevous version: `img src="{{ news-image }}"`
this version: `img src={{ news-image }}`
Also, on  news-group.scss. I removed the media query for the selector used in the Gray Example, because the gray background needs to show on all breakpoints. The white clipped corner isn't visible without it.

updated images  with img src={{ news-image }}

---

components/01-visual-styling/03-button/02-button/button.scss
components/01-visual-styling/03-button/03-angled-button/angled-button.scss
components/02-components/03-card/01-action-card/action-card.hbs
components/02-components/03-card/01-action-card/action-card.scss
components/02-components/03-card/02-event-card/event-card.scss
components/02-components/03-card/03-content-card/content-card--blue.hbs
components/02-components/03-card/03-content-card/content-card.hbs
components/02-components/03-card/03-content-card/content-card.scss
components/02-components/03-card/04-news-card/news-card.scss
components/02-components/04-profile/01-profile-card/profile-card--blue.hbs
components/02-components/04-profile/01-profile-card/profile-card.hbs
components/02-components/04-profile/01-profile-card/profile-card.scss
components/02-components/04-profile/03-profile-info/profile-info.scss
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss
components/03-sections/05-content-group/06-link-list/link-list.scss

removing the global a {text-decoration:none} resulted in cards and buttons rendering with underlines.  for these specific components, anchors should have no decoration

fixing anchor text decorations, fixes #199

---

components/02-components/02-tab/tab.hbs
components/02-components/02-tab/tab.scss

Removed anchor underline on tab label. Adjusted the tab <li> background color to prevent white from showing on inactive tabs when active tab label is more than one line.

Fixed label and tab background color

---

components/01-visual-styling/03-button/03-angled-button/angled-button--blue.hbs
components/01-visual-styling/03-button/03-angled-button/angled-button--large.hbs
components/01-visual-styling/03-button/03-angled-button/angled-button.hbs
components/01-visual-styling/03-button/03-angled-button/angled-button.scss
components/02-components/03-card/01-action-card/action-card.hbs
components/02-components/03-card/01-action-card/action-card.scss
components/02-components/04-profile/01-profile-card/profile-card.hbs
components/02-components/04-profile/01-profile-card/profile-card.scss
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--2up.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--blue-2up.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--blue.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--colors.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--grey.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--orange-2up.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons--orange.hbs
components/03-sections/04-call-to-actions/01-call-to-action-buttons/call-to-action-buttons.hbs
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action--alt.hbs
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action.hbs
components/03-sections/04-call-to-actions/03-enrollment-call-to-action/enrollment-call-to-action.scss

Talked to Lallo, removed btn-icon CSS for now. Was causing some issues in the multiple button/action card components. Could fix but not worth reworking those unless we're sure we want to use the angled buttons in the WYSIWYG editor.
Minor other fixes. Added some padding to profile description. Adjusted font sizes in some callouts.

Minor CSS fixes, Added arrow icon back for now

---

components/02-components/02-tab/tab.config.json
components/02-components/02-tab/tab.hbs
components/02-components/02-tab/tab.scss
components/03-sections/01-accordion/accordion.hbs
components/03-sections/01-accordion/accordion.scss

- added more tabs and longer tab names for testing
- added more content to the tab to test -content styling
- removed padding and 85% width
- added bootstrap media breakpoints to go 100% tab heading widths on sizes md and down (768px and lower)
- moving hard coded margin-right: 5px on tab heading to only sizes above md which was causing weird tab break issues see #311 
- getting -content classes in sync with .accordion changes
- adding orange color to headings for both components w/o need of a additional class name

311 tab component inner styling

---

components/01-visual-styling/03-button/01-text-link/text-link.scss
components/02-components/03-card/02-event-card/event-card.scss

Fixed issue with H2's in text link components being blue over a blue background.
Bigger issue: It seems that horizontal event (individual and listing) component is structured in a way that the whole component links to the event page/info. This causes it to inherit the <a> hover styles, which means it currently turns completely grey on hover. I added some component specific CSS to have the grey be trasparent on hover for now, but we could talk about if there's a better way to handle this.

Text link color fix, Horizontal Event Component fix

---

components/03-sections/01-accordion/accordion.scss

Requested in Issue: https://github.com/utsa-asc/college-dls/issues/348
Reversed styles of accordion heading to make collapsed state light and expanded state dark.
Screenshot of changes in appearance:

348: accordion - updated color scheme: 

---

components/01-visual-styling/02-typography/01-headline/headline.scss
components/01-visual-styling/02-typography/04-intro/intro.hbs
components/01-visual-styling/02-typography/04-intro/intro.scss

OK, hoping to address a couple of things here.
I updated the sizes of the H tags to rem sizes instead of pixels. The rem sizes are either the same or pretty close to the pixel equivalent, so they should work fine for the actual headers. We might just have to look out for a component here or there that's using an h tag (or an equivalent size) and update it to the rem size if needed.
I also adjusted the CSS to separate the h tags and the .h classes because that wasn't allowing the .orange class to overwrite the blue color on the headers (it's one of the issues on github).
Lastly, I noticed that on the admissions pages that are currently being worked on ( for example, https://futurenew.flywheelsites.com/freshman/admissions/) they are essentially using the h-tags to create a sort of intro …

Headline sizing updates, Separating H classes

---

components/01-visual-styling/04-utility/06-misc/misc.hbs

follow up edit that I left out, now that there are image examples on this page, we no longer need the older css-box block

removing outdated examples

---

components/01-visual-styling/05-branding-standards/01-global-header/global-header.hbs
components/01-visual-styling/05-branding-standards/01-global-header/global-header.scss
public/js/college-dls.min.js
src/js/script.js

@jampafoo, try this PR out and let me know if this works on future, changes:
- script.js updated to target #header for the toggle instead of body tag
- css changes, padding-top expansion updated to #header.search-bar-active for the change above
- html code, removed everything but the vanilla classes for bootstrap on the dropdown menu:
` <div class="dropdown-menu " ...`

423 global header search toggle

---

public/js/college-dls.min.js
src/js/script.js

Sticky nav only shows on scroll up. Also, I did notice the blue utility nav only shows at the top of the page. Maybe we could have it displayed as part of the sticky nav. It seems the users might need the search at some point, and having it more accessible would help.

Addressed issue #429 with sticky nav on scroll up

---

components/02-components/02-tab/tab.config.json
components/02-components/02-tab/tab.hbs

Added h2 group title to tabs as well. Styled it the same way as accordion group title.
Mobile: 
Desktop:

added h2 title to entire tab group

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss

Added a `white-space: normal` for `.dropdown-item` on small breakpoint. Addresses issue #485

Fixed issue #485

---

.github/workflows/build-deploy.yml
.github/workflows/deploy-preview.yml

necessary updates in order to support node12->16 for GitHub actions using node

updating actions versions for node16 dep

---

src/js/profile.js

@lalov1 example of a publications reverse chrono sort based on the currentItem.PublishDate, modified the convertDate function to only return formatted year (yyyy).
addresses issue #532

only output full year, reverse chrono sort publications

---

components/03-sections/02-navigation/03-side-navigation/side-navigation.hbs
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss

first attempt at resolving issue #489.  Will require removal of anchor on menu dropdown in CMS formats:
[College-PROTOTYPE/_cms/formats/components/sideNavigation](https://walledev.it.utsa.edu/entity/open.act?id=d1f6412a81736a1b3be11e0611458b58&type=format)

removing nested anchors on menu dropdown items

---

components/01-visual-styling/02-button/03-angled-button/angled-button.scss
components/02-components/03-card/01-action-card/action-card--long-copy.hbs
components/03-sections/05-content-group/00-action-group/action-group.hbs

fixes for #560, dropping pixels for REMs seems to fix this for multiple lines
https://utsa-asc.github.io/college-dls/560-dls-action-button-display-issue-when-wraps-to-two-lines/components/detail/action-group--default

560 dls action button display issue when wraps to two lines

---

components/04-reference-pages/14-internal-error-page/internal-error-page.config.json

Changed json file name to **internal-error-page.config.json** to get status to display correctly.
Now would be a good time to finally figure out what's going on with the css in Cascade DLS that is preventing it from working there as well, I guess.  - (That's sep from working here in DLS)

601 - added .config.json to file name

---

components/02-components/02-tab/tab.hbs

Added `role="tablist"` and `role="presentation"` to pass accessibility tests. 
Change made, and the issue is no longer showing: 
https://utsa.dubbot.com/sites/632ca47e7e251f00019d8e30/pages/6362ebc22593033cc743f294

Added items to past a11y tests

---

components/04-reference-pages/15-error-page-not-found/error-page-not-found.config.json
components/04-reference-pages/15-error-page-not-found/error-page-not-found.hbs

For some reason I had originally commented out  
``.
Removed `` around it to add it back in to match the page display in Cascade.

<section> @banner--slim </section> added

---

components/02-components/03-card/01-action-card/action-card--grey.hbs
components/02-components/03-card/01-action-card/action-card.hbs
components/03-sections/05-content-group/00-action-group/action-group--compact-grey.hbs
components/03-sections/05-content-group/00-action-group/action-group--compact.hbs
components/03-sections/05-content-group/00-action-group/action-group--grey.hbs
components/03-sections/05-content-group/00-action-group/action-group.config.json
components/03-sections/05-content-group/00-action-group/action-group.hbs
components/03-sections/05-content-group/00-action-group/action-group.readme.md
components/03-sections/05-content-group/00-action-group/action-group.scss

First stab at this....On large and up displays made the cards col-lg-3. Cards also center on large and up displays.
I think the logic in Cascade will need to have this condition for large and up displays -
4 cards in a row: `<div class="col-lg-3 col-md-6 col-sm-12">`
but if
3 cards in a row: `<div class="col-lg-4 col-md-6 col-sm-12">`
But do we make it a users choice? An option to choose between 3 or 4 cards per row in the component block? Or just do it automatically with formatting magic? 
If user has 7 cards, can one row be 4 cards and the other 3 cards?  Probably at that point they would need to make two separate action card components?

Action Cards - Make 4 per row on larger devices

---

components/03-sections/07-quickfacts/quickfacts--5up.hbs
components/03-sections/07-quickfacts/quickfacts.config.json
components/03-sections/07-quickfacts/quickfacts.scss

Added 5up variant. It has SCSS that removes last child from 6up display that is only needed for DLS (do not need to bring into  CMS...I don't think, anyway.)

Added 5up variant

---

components/01-visual-styling/01-typography/05-ordered-list/ordered-list--alt.hbs
components/01-visual-styling/01-typography/05-ordered-list/ordered-list.hbs
components/01-visual-styling/01-typography/05-ordered-list/ordered-list.scss
components/01-visual-styling/01-typography/06-unordered-list/unordered-list.hbs
components/01-visual-styling/01-typography/06-unordered-list/unordered-list.scss
components/03-sections/02-navigation/03-side-navigation/side-navigation.scss
components/04-reference-pages/12-stacked-testing/stacked-testing.hbs

Updated the list styles so they would be applied to all lists within the body of the page without the need to add a class. Updated side nav CSS to compensate for that. Styles now scoped to lists within the page-text-wrapper.
Kept enhanced list and alt ordered list CSS since those are different.

Updated lists CSS so styles are applied without classes

---

components/03-sections/07-quickfacts/quickfacts--grey.hbs

It looks like the h3 class was already there, so the size will be the same. The numbers are h2's, so still not technically semantic when the title is added.

Changed h3 to h2

---

components/03-sections/03-banner/banner--rotating.hbs
components/03-sections/03-banner/banner.config.json
components/03-sections/03-banner/banner.scss
public/college/images/placeholders/placeholder-1200-600-blue.svg
public/college/images/placeholders/placeholder-1200-600-orange.svg
public/college/images/placeholders/placeholder-1600-500.svg
src/scss/_vendor.scss

- added some placeholder images to test stretching (SVG)
- found some lingering styles from _vendor.scss that was overriding pause button location on some screen sizes
- affixing pause button to the right hand side, more like video, we are restricted with how far right we can go due to the next/back button controls
- affixing the indicator controls to the same line at the bottom
- cleaning up rotating banner hbs to be more hbs
- added dummy context data for rotating to config
- added 40em height to wrapper (.hero-banner-slider) to conform to same ratio as video-banner

cleaning button and controls styling, addresses issue #673

---

components/02-components/03-card/02-event-card/event-card--horizontal-blue.hbs
components/02-components/03-card/02-event-card/event-card--horizontal-image-blue.hbs
components/02-components/03-card/02-event-card/event-card--horizontal-image.hbs
components/02-components/03-card/02-event-card/event-card--horizontal.hbs
components/02-components/03-card/02-event-card/event-card.scss

Removed the image that was being used to add the arrow on the event card with CSS/FA code. Updated all event card variants. Tested and working on Chrome.

Replaced Event Card arrow png with FA and CSS

---

components/02-components/04-profile/01-profile-card/profile-card.scss

Made profile card 'Name' blue by default. If linked, 'Name' should be orange and behave as usual (link hover, etc.). Meant to differentiate between profiles that are linked to a profile page and profiles that aren't.
Also updated the blue background version to use a grey instead of white. Might have to look at other options if it's too hard to differentiate between the grey and the white, but also I don't think we use the blue bg much.
CDLS cards are built to all be linked in the handlebars file. When I remove the link in chrome inspector the name is a plain blue, so I think it works.

Updated Profile Card CSS. Linked/Not Linked.

---

components/02-components/03-card/01-action-card/action-card--grey.hbs
components/02-components/03-card/01-action-card/action-card.hbs
components/02-components/03-card/01-action-card/action-card.scss

Updated Action Card CSS for dark mode. The action cards always seem to have a white bg, so I think simply adding CSS for ul li as I have done in the action card CSS is enough, but just in case I also added CSS for dark mode.

788-dm-uls-not-displaying-correctly-on-action-cards

---

components/01-visual-styling/01-typography/01-headline/headline.scss
components/04-reference-pages/09-events-page/events-page.scss

Updated dark mode CSS for events page. Had to add some redundancies for H tags because I think they get overwritten in dark mode somehow. Also specified h class sizes in the typography page because that was also being lost somewhere.
I *think* this should solve all the white/orange text issues.

769-dm-events-details-page-is-unstyled-for-dark-mode

---

components/04-reference-pages/08-news-page/news-page.scss
components/04-reference-pages/09-news-listing-page/news-listing-page.scss

extra styles added for news listings was overriding DM styles for news-text-blocks.  closes #804

DM styling for news article body text

---

components/03-sections/06-blockquote/blockquote.scss

Updated blockquote DM CSS to change blockquote footer, name/title, from grey to white to improve color contrast for accessibility.

852-dm-blockquote-with-orange-background-has-a-contrast-error

---

components/01-visual-styling/01-typography/06-table/table.scss

- Refactored code for better readability 
- Added coverage for headers
Hopefully, this is the last table update, but we could refactor the code slightly more. It is hard to support the different tables, and we might also need to look at the Bootstrap classes.

866 dm headers not showing correctly on striped background

---

components/03-sections/10-icon-callout/icon-callout--white.hbs
components/03-sections/10-icon-callout/icon-callout.scss

Changed the coverage from duotone to `.fa-6x` to cover items outside the duotone items since users could add any font awesome icon.

Added coverage for items outside of the duotone items

---

components/03-sections/03-banner/banner.scss

The overlay is causing issues with the mobile nav. I removed the top value, but let me know if there is a better way to do this.

Removed top value, so carousel doesn't overlay nav

---

src/scss/_font.scss

quick fix to get dls back in working order, latest version of FA-pro no longer has a separate file for duotone-icons

duotone-icons no longer in upstream

---

components/03-sections/02-navigation/01-site-navigation/site-navigation.scss

I'm unsure if we should add the emergency banner to the DLS, but this should work for now.

Added coverage for emergency banner in dark mode

---

components/03-sections/06-blockquote/blockquote--blue-image-heading.hbs
components/03-sections/06-blockquote/blockquote.scss

Added variant for Blockquote Image with a blue background and white h3. For some reason it wouldn't pick it up until I added h-tag `.blockquote-heading h3` specificity to the css selector.

929-DLS blockquote image variant with blue bg and white h3

---

components/03-sections/03-banner/banner.scss

Added CSS rule to decrease header title font size so longer titles fit better on mobile screens. Hopefully this keeps 99.9% of words from getting cut off.

Issue 953 - Smaller header title size for mobile screens
